---
# File: tasks/main.yml - Tasks for Meatspace Chat role

- name: Update OS package cache
  sudo: True
  apt: update-cache=yes
  tags:
    - system_packages

- name: Install OS packages
  sudo: True
  apt: "pkg={{ item }} state=installed"
  with_items: meatspacechat_os_packages
  tags:
    - system_packages

- name: Download ØMQ
  get_url: "url=http://download.zeromq.org/{{ meatspacechat_zeromq_pkg }} dest=/tmp/"
  tags: zeromq

- name: Prepare ØMQ
  shell: "tar zxf {{ meatspacechat_zeromq_pkg }} chdir=/tmp creates=/tmp/{{ meatspacechat_zeromq }}"
  tags:
    - zeromq

- name: Configure ØMQ
  shell: "./configure chdir=/tmp/{{ meatspacechat_zeromq }}"
  tags:
    - zeromq

- name: Build ØMQ
  shell: "make chdir=/tmp/{{ meatspacechat_zeromq }}"
  tags:
    - zeromq

- name: Install ØMQ
  sudo: True
  shell: "make install {{ meatspacechat_zeromq }} chdir=/tmp/{{ meatspacechat_zeromq }}"
  ignore_errors: yes
  tags:
    - zeromq

- name: Update shared libs
  sudo: True
  shell: "ldconfig"

- name: Install Node Version Manager
  sudo: False
  git: "repo=https://{{ meatspacechat_nvm_repo }} dest=/home/{{ meatspacechat_admin }}/.nvm"
  tags:
    - node_packages

- name: Install Node.js
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm install {{ meatspacechat_node_version }} creates={{ meatspacechat_node_dir }} executable=/bin/bash"
  tags:
    - node_packages

- name: Clone Meatspace Chat repository
  sudo: False
  git: "repo=git://{{ meatspacechat_repo }} dest={{ meatspacechat_dir }}"

- name: Define Meatspace Chat configuration
  sudo: False
  template: "src=local.json.j2 dest={{ meatspacechat_dir }}/local.json"
  template: "src=clients.json.j2 dest={{ meatspacechat_dir }}/clients.json"
  template: "src=whitelist.json.j2 dest={{ meatspacechat_dir }}/whitelist.json"
  tags:
    - meatspacechat_config

- name: Install Meatspace Chat NPM items
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm use {{ meatspacechat_node_version }} && npm install chdir={{ meatspacechat_dir }}"
  tags:
    - node_packages

- name: Install Bower
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm use {{ meatspacechat_node_version }} && npm install -g bower chdir={{ meatspacechat_dir }}"
  tags:
    - node_packages

- name: Install Nodemon
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm use {{ meatspacechat_node_version }} && npm install -g nodemon chdir={{ meatspacechat_dir }}"
  tags:
    - node_packages

- name: Install Bower packages
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm use {{ meatspacechat_node_version }} && bower install chdir={{ meatspacechat_dir }}"
  tags:
    - node_packages

- name: Grunt build
  sudo: False
  shell: ". /home/{{ meatspacechat_admin }}/.nvm }}/nvm.sh && nvm use {{ meatspacechat_node_version }} && npm run-script grunt build chdir={{ meatspacechat_dir }}"


- name: Create upstart script
  sudo: True
  template: "src=start_meatspacechat.sh.j2 dest={{ meatspacechat_dir }}/start_meatspacechat.sh mode=0755"

- name: Create upstart configuration
  sudo: True
  template: src=meatspacechat.conf.j2 dest=/etc/init/meatspacechat.conf

- name: Start Meatspace Chat
  sudo: True
  service: name=meatspacechat state=started
  tags:
    - meatspacechat_service

