---
# File: tasks/main.yml - Tasks for Meatspace Chat role

- name: Update OS package cache
  sudo: True
  apt: update-cache=yes
  tags:
    - system_packages

- name: Install OS packages
  sudo: True
  apt: "pkg={{ item }} state=installed"
  with_items: meatspace-chat_os_packages
  tags:
    - system_packages

- name: Download ØMQ
  get_url: "url=http://download.zeromq.org/{{ meatspace-chat_zeromq_pkg }} dest=/tmp/"
  tags: zeromq

- name: Prepare ØMQ
  shell: "tar zxf {{ meatspace-chat_zeromq_pkg }} chdir=/tmp creates=/tmp/{{ meatspace-chat_zeromq }}"
  tags:
    - zeromq

- name: Configure ØMQ
  shell: "./configure chdir=/tmp/{{ meatspace-chat_zeromq }}"
  tags:
    - zeromq

- name: Build ØMQ
  shell: "make chdir=/tmp/{{ meatspace-chat_zeromq }}"
  tags:
    - zeromq

- name: Install ØMQ
  sudo: True
  shell: "make install {{ meatspace-chat_zeromq }} chdir=/tmp/{{ meatspace-chat_zeromq }}"
  ignore_errors: yes
  tags:
    - zeromq

- name: Update shared libs
  sudo: True
  shell: "ldconfig"

- name: Install Node Version Manager
  sudo: False
  git: "repo=https://{{ meatspace-chat_nvm_repo }} dest=/home/{{ meatspace-chat_admin }}/.nvm"
  tags:
    - node_packages

- name: Install Node.js
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm install {{ meatspace-chat_node_version }} creates={{ meatspace-chat_node_dir }} executable=/bin/bash"
  tags:
    - node_packages

- name: Clone Meatspace Chat repository
  sudo: False
  git: "repo=git://{{ meatspace-chat_repo }} dest={{ meatspace-chat_dir }}"

- name: Install Meatspace Chat NPM items
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm use {{ meatspace-chat_node_version }} && npm install chdir={{ meatspace-chat_dir }}"
  tags:
    - node_packages

- name: Install Bower
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm use {{ meatspace-chat_node_version }} && npm install -g bower chdir={{ meatspace-chat_dir }}"
  tags:
    - node_packages

- name: Install Nodemon
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm use {{ meatspace-chat_node_version }} && npm install -g nodemon chdir={{ meatspace-chat_dir }}"
  tags:
    - node_packages

- name: Install Bower packages
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm use {{ meatspace-chat_node_version }} && bower install chdir={{ meatspace-chat_dir }}"
  tags:
    - node_packages

- name: Grunt build
  sudo: False
  shell: ". /home/{{ meatspace-chat_admin }}/.nvm/nvm.sh && nvm use {{ meatspace-chat_node_version }} && npm run-script grunt build chdir={{ meatspace-chat_dir }}"

- name: Define Meatspace Chat configuration
  sudo: False
  template: "src=local.json.j2 dest={{ meatspace-chat_dir }}/local.json"
  template: "src=clients.json.j2 dest={{ meatspace-chat_dir }}/clients.json"
  template: "src=whitelist.json.j2 dest={{ meatspace-chat_dir }}/whitelist.json"
  tags:
    - meatspace-chat_config

- name: Create upstart script
  sudo: True
  template: "src=start_meatspace-chat.sh.j2 dest={{ meatspace-chat_dir }}/start_meatspace-chat.sh mode=0755"

- name: Create upstart configuration
  sudo: True
  template: src=meatspace-chat.conf.j2 dest=/etc/init/meatspace-chat.conf

- name: Start Meatspace Chat
  sudo: True
  service: name=meatspace-chat state=started
  tags:
    - meatspace-chat_service

