---
# File: tasks/main.yml - Tasks for Meatspace Chat role

- name: Update OS package cache
  sudo: True
  apt: update-cache=yes
  tags:
    - system_packages

- name: Install OS packages
  sudo: True
  apt: "pkg={{ item }} state=installed"
  with_items: meatspace_chat_os_packages
  tags:
    - system_packages

- name: Download ØMQ
  get_url: "url=http://download.zeromq.org/{{ meatspace_chat_zeromq_pkg }} dest=/tmp/"
  tags: zeromq

- name: Prepare ØMQ
  command: "tar zxf {{ meatspace_chat_zeromq_pkg }} chdir=/tmp creates=/tmp/{{ meatspace_chat_zeromq }}"
  tags:
    - zeromq

- name: Configure ØMQ
  command: "./configure chdir=/tmp/{{ meatspace_chat_zeromq }} creates=/tmp/{{ meatspace_chat_zeromq }}/Makefile"
  tags:
    - zeromq

#- name: Build ØMQ
#  command: "make chdir=/tmp/{{ meatspace_chat_zeromq }}"
#  tags:
#    - zeromq

- name: Install ØMQ
  sudo: True
  command: "make install {{ meatspace_chat_zeromq }} chdir=/tmp/{{ meatspace_chat_zeromq }} creates=/usr/local/lib/libzmq.so"
  ignore_errors: yes
  tags:
    - zeromq

- name: Update shared libs
  sudo: True
  command: "ldconfig"

- name: Install NVM
  sudo: False
  git: "repo=https://{{ meatspace_chat_nvm_repo }} dest={{ meatspace_chat_nvm_dir }}"
  tags:
    - node_packages

- name: Install Node.js
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh && nvm install {{ meatspace_chat_node_version }} creates={{ meatspace_chat_node_dir }} executable=/bin/bash"
  tags:
    - node_packages

- name: Clone Meatspace Chat
  sudo: False
  git: "repo=git://{{ meatspace_chat_repo }} dest={{ meatspace_chat_dir }}"

- name: Install NPM items
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh executable=/bin/bash && nvm use {{ meatspace_chat_node_version }} executable=/bin/bash && npm install chdir={{ meatspace_chat_dir }} executable=/bin/bash"
  tags:
    - node_packages

- name: Install Bower
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh && nvm use {{ meatspace_chat_node_version }} && npm install -g bower executable=/bin/bash"
  tags:
    - node_packages

- name: Install Nodemon
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh && nvm use {{ meatspace_chat_node_version }} && npm install -g nodemon executable=/bin/bash"
  tags:
    - node_packages

- name: Install Bower packages
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh && nvm use {{ meatspace_chat_node_version }} && bower install chdir={{ meatspace_chat_dir }} executable=/bin/bash"
  tags:
    - node_packages

- name: Grunt build
  sudo: False
  command: ". {{ meatspace_chat_nvm_dir }}/nvm.sh && nvm use {{ meatspace_chat_node_version }} && npm run-script grunt build chdir={{ meatspace_chat_dir }} executable=/bin/bash"

- name: Meatspace Chat locals
  sudo: False
  template: "src=local.json.j2 dest={{ meatspace_chat_dir }}/local.json owner={{ meatspace_chat_admin }} group={{ meatspace_chat_admin }} mode=0644"

- name: Meatspace Chat clients
  sudo: False
  template: "src=clients.json.j2 dest={{ meatspace_chat_dir }}/clients.json owner={{ meatspace_chat_admin }} group={{ meatspace_chat_admin }} mode=0644"

- name: Meatspace Chat whitelist
  sudo: False
  template: "src=whitelist.json.j2 dest={{ meatspace_chat_dir }}/whitelist.json owner={{ meatspace_chat_admin }} group={{ meatspace_chat_admin }} mode=0644"
  tags:
    - meatspace_chat_config

- name: Create upstart configuration
  sudo: True
  template: src=meatspace-chat.conf.j2 dest=/etc/init/meatspace-chat.conf

- name: Create upstart script
  sudo: True
  template: "src=start_meatspace-chat.sh.j2 dest={{ meatspace_chat_dir }}/start_meatspace-chat.sh mode=0755"

- name: Start Meatspace Chat
  sudo: True
  service: name=meatspace-chat state=restarted
  tags:
    - meatspace_chat_service

