---
# handlers/main.yml Handlers for Meatspace Chat role

- name: restart meatspace_chat
  service: name=meatspace_chat state=restarted

- name: start meatspace_chat
  service: name=meatspace_chat state=started

- name: stop meatspace_chat
  service: name=meatspace_chat state=stopped

